- hosts: app-server
  become: yes
  tasks:
  - name: Install python3 and virtualenv
    apt:
      name:
        - python3
        - virtualenv
      update_cache: yes
  - name: Install django with pip
    pip:
      virtualenv: /home/ubuntu/workspace/venv
      name: 
        - django
        - djangorestframework
  - name: Setup django project
    shell: '. /home/ubuntu/workspace/venv/bin/activate; django-admin startproject myproject /home/ubuntu/workspace/'
  - name: Allowed hosts django project
    lineinfile:
      path: /home/ubuntu/workspace/myproject/settings.py
      regexp: 'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS = ["*"]'
      backrefs: yes